#!/usr/bin/env python3
"""Derive the preprint appendix from the unchanged canonical supplement."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def expected_appendix():
    original = (ROOT / 'proofs/reference-results.tex').read_text()
    body = original.split('\\maketitle\n', 1)[1].rsplit('\\end{document}', 1)[0]
    body = body.replace('\\section{', '\\subsection{')
    body = body.replace('\\label{eq:binomial}', '\\label{eq:supplement-binomial}')
    body = body.replace('\\eqref{eq:binomial}', '\\eqref{eq:supplement-binomial}')
    return ('% Generated by scripts/prepare_mathematical_appendix.py from the canonical supplement.\n'
            '\\section{Mathematical supplement}\\label{app:mathematical-supplement}\n' + body)


if __name__ == '__main__':
    path = ROOT / 'paper/mathematical-supplement.tex'
    expected = expected_appendix()
    if not path.exists() or path.read_text() != expected:
        path.write_text(expected)
    print('Preprint appendix agrees with the canonical mathematical supplement.')
